apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloudrun-app-pipeline
description: Cloud Deploy pipeline to Cloud Run

serialPipeline:
  stages:
    - targetId: dev
      profiles: [dev]
      strategy:
        standard:
          verify: false
    - targetId: qa
      profiles: [qa]
      strategy:
        standard:
          verify: true
    - targetId: prod
      profiles: [prod]
      strategy:
        standard:
          verify: true
          # This one will require manual approval
          # Add requireApproval: true below if you want approvals
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Cloud Run dev environment
run:
  location: projects/clear-booking-470907-q6/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qa
description: Cloud Run QA environment
run:
  location: projects/clear-booking-470907-q6/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: Cloud Run prod environment
run:
  location: projects/clear-booking-470907-q6/locations/asia-south1
