# ==============================
# Delivery Pipeline
# ==============================
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloudrun-app-pipeline1
description: Cloud Run pipeline with repair/failover automation
serialPipeline:
  stages:
    - targetId: dev
      profiles: [dev]
    - targetId: qa
      profiles: [qa]
    - targetId: prod
      profiles: [prod]

# ==============================
# Automation for repair/failover
# ==============================
---
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: cloudrun-app-pipeline1/repair-rollout
description: Automatically retries failed rollouts and rolls back if retries fail
suspended: false
serviceAccount: 764196271662-compute@developer.gserviceaccount.com
selector:
  targets:
    - id: prod
rules:
  - repairRolloutRule:
      name: repair-rollout
      repairPhases:
        - retry:
            attempts: 3
            wait: 1m
            backoffMode: LINEAR
        - rollback:
            destinationPhase: "stable"

# ==============================
# Targets
# ==============================
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Cloud Run dev environment
run:
  location: projects/divine-course-470809-f6/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qa
description: Cloud Run qa environment
run:
  location: projects/divine-course-470809-f6/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: Cloud Run prod environment
run:
  location: projects/divine-course-470809-f6/locations/asia-south1
