apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloudrun-app-pipeline
description: Cloud Run pipeline with fully automated canary deployment on prod
serialPipeline:
  stages:
    - targetId: dev
      profiles: [dev]
    - targetId: qa
      profiles: [qa]
    - targetId: prod
      profiles: [prod]
      strategy:
        canary:
          runtimeConfig:
            cloudRun:
              automaticTrafficControl: true
          canaryDeployment:
            percentages: [10,50,100]
            verify: false
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Cloud Run dev environment
run:
  location: projects/clear-booking-470907-q6/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qa
description: Cloud Run qa environment
run:
  location: projects/clear-booking-470907-q6/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: Cloud Run prod environment
run:
  location: projects/clear-booking-470907-q6/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: cloudrun-app-pipeline/auto-advance-canary
description: Automatically advance canary rollout from 10% → 50% → 100%
suspended: false
serviceAccount: 326372984052-compute@developer.gserviceaccount.com
selector:
  targets:
    - id: prod
rules:
  - advanceRolloutRule:
      name: auto-advance-canary
      sourcePhases: ["10%", "50%"]   # Names of your phases (phase names are labels in canaryDeployment)
      wait: 1m                      # Wait 1 minute after phase completes
