# ==============================
# Delivery Pipeline
# ==============================
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloudrun-app-pipeline
description: Cloud Run pipeline with automatic repair + rollback
serialPipeline:
  stages:
    - targetId: dev
      profiles: [dev]
    - targetId: qa
      profiles: [qa]
    - targetId: prod
      profiles: [prod]
      # ✅ Add rollback policy for prod stage itself
      strategy:
        standard:
          failurePolicy:
            retry: true       # Will retry deployment automatically
            rollback: true    # Will rollback to previous successful release if retries fail

# ==============================
# Automation for repair/failover
# ==============================
---
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: cloudrun-app-pipeline/repair-rollout
description: Automatically retries failed rollouts and rolls back if retries fail
suspended: false
serviceAccount: 326372984052-compute@developer.gserviceaccount.com
selector:
  targets:
    - id: prod
rules:
  - repairRolloutRule:
      name: repair-rollout
      repairPhases:
        - retry:
            attempts: 3           # 3 retry attempts
            wait: 1m              # Wait 1 minute between attempts
            backoffMode: LINEAR   # Linear backoff (1m, 2m, 3m)
        - rollback:
            # ✅ No need to specify destinationPhase for standard strategy rollback,
            # it will redeploy the last good release
            destinationPhase: ""  # Empty = rollback entire release

# ==============================
# Targets
# ==============================
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Cloud Run dev environment
run:
  location: projects/divine-course-470809-f6/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qa
description: Cloud Run qa environment
run:
  location: projects/divine-course-470809-f6/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: Cloud Run prod environment
run:
  location: projects/divine-course-470809-f6/locations/asia-south1
