apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloudrun-app-pipeline
description: Cloud Run pipeline with automated time-based promotion
serialPipeline:
  stages:
    - targetId: dev
      profiles: [dev]
    - targetId: qa
      profiles: [qa]
    - targetId: prod
      profiles: [prod]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Cloud Run dev environment
run:
  location: projects/clear-booking-470907-q6/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qa
description: Cloud Run qa environment
run:
  location: projects/clear-booking-470907-q6/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: Cloud Run prod environment
run:
  location: projects/clear-booking-470907-q6/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: cloudrun-app-pipeline/timed-promote-dev-to-qa
description: Timed auto promotion from dev → qa every 2 minutes
suspended: false
serviceAccount: 326372984052-compute@developer.gserviceaccount.com
selector:
  targets:
  - id: dev
rules:
- timedPromoteReleaseRule:
    name: auto-timed-promote-to-qa
    toTargetId: qa
    schedule: "*/2 * * * *"   # every 2 minutes
---
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: cloudrun-app-pipeline/timed-promote-qa-to-prod
description: Timed auto promotion from qa → prod every 2 minutes
suspended: false
serviceAccount: 326372984052-compute@developer.gserviceaccount.com
selector:
  targets:
  - id: qa
rules:
- timedPromoteReleaseRule:
    name: auto-timed-promote-to-prod
    toTargetId: prod
    schedule: "*/2 * * * *"   # every 2 minutes
