apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloudrun-app-pipeline
description: Cloud Run pipeline with canary deployment on prod
serialPipeline:
  stages:
    - targetId: dev
      profiles: [dev]
    - targetId: qa
      profiles: [qa]
    - targetId: prod
      profiles: [prod]
      strategy:
        canary:
          runtimeConfig:
            cloudRun:
              automaticTrafficControl: true
          automatedRollout: true    
          customCanaryDeployment:
            phaseConfigs:
              - phaseId: "warmup-cr"
                percentage: 10
                profiles: ["prod"]
                verify: false
              - phaseId: "scaling-cr"
                percentage: 50
                profiles: ["prod"]
                verify: false
              - phaseId: "stable"
                percentage: 100
                profiles: ["prod"]
                verify: false
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Cloud Run dev environment
run:
  location: projects/clear-booking-470907-q6/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qa
description: Cloud Run qa environment
run:
  location: projects/clear-booking-470907-q6/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: Cloud Run prod environment
run:
  location: projects/clear-booking-470907-q6/locations/asia-south1
